project:
  type: website
  output-dir: docs

website:
  title: "Fabian BÃ¼hler"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "IMP Klasse 11"
        href: 11imp/11imp.qmd
      - text: "PK Programmieren"
        href: pk-programmieren/pk-prog.qmd

  sidebar:
    - title: "PK Programmieren"
      style: "docked"
      search: false
      contents:
        - pk-programmieren/pk-prog.qmd
        - pk-programmieren/pk-prog_einfPython.qmd
      
    - title: "IMP Klasse 11"
      contents:
        - 11imp/11imp.qmd
        - 11imp/11imp-Loesungen.qmd
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



